### PR TITLE
refactorings on bag-store

### PR DESCRIPTION
**Pull request by rvanheest**
@janvanmansum 

* [x] self-type annotations/cake pattern
* [x] some for-comprehension refactorings
* [x] unused fetchTxt
* [x] `Try` in enum functions
* [x] move all exceptions to `package.scala`
* [x] `org.scalatest.Inside` as mixin trait rather than import
* [x] remove implicits
* [x] remove unnecessary `iterator` calls
* [x] make the code better readable in some places
* [x] `toBagId` and `toFileId` as methods on the abstract class rather than static functions in the companion object
* [x] add `.github` folder with PR template

### CODE REVIEW

**Comment by janvanmansum** [comment]
@rvanheest : are you finished with this one? Note that I can see you didn't run the build as there are missing license headers ;)

**Comment by rvanheest** [comment]
Indeed I didn't try to build 😉
in fact, I got some questions still, which are in Skype. Tried to contact you over the course of the day, but I just noticed that you were already gone.

Currently I'm further applying the cake pattern to this project. For now as an experiment and demo and not part of this PR. I can show you some results of it already and will do a PR of that if you like it.

**Comment by janvanmansum** [comment]
Let's look at it tomorrow. Let's get some closure here first. This PR is getting pretty large. 

Btw. please upgrade to the `dans-scala-prototype` 1.40. Part of the license-problems is due to the fact that some extension weren't ignored yet.

**Comment by janvanmansum** [comment]
Well, the tests are still passing. So I am sure we'll be fine. :)

**Comment by rvanheest** [comment]
Sure, I'll do that before adding the license headers

**Comment by rvanheest** [comment]
maybe also add travis support to this repo?

**Comment by janvanmansum** [comment]
Yep, as soon as we make it public again.

**Comment by rvanheest** [comment]
👍

**Comment by rvanheest** [comment]
I added the missing license header. Maybe we can go through it together tomorrow morning before you merge it? Especially some of the rewrites in 78b626b. IMHO these improve the readability of the code very much!

**Review by janvanmansum — APPROVED** [review]
Good job! Greatly improved. The only downside to reformatting so much code is that it is hard to find the places where you actually changed logic or solved bugs. We should definitely have some standards for code formatting and preferably a profile for IntelliJ to automate it as much as possible.

**Pull request merged**
